kind: pipeline
name: drone test
type: docker
    
# 代码编译
steps:
  - name: build
    image: maven:3-jdk-10
    pull: if-not-exists
    commands:
      - mvn clean package   # 清洁打包 因为java项目需要编译后才能进行代码扫描
    when:
      branch: dev
